export const STARTER_PHOTOS: { url: string; label: string; category: string }[] = [
  { url: "/starter-photos/jacksonville-skyline-golden.jpg", label: "Jacksonville skyline", category: "Place" },
  { url: "/starter-photos/jacksonville-sunset-aerial.jpg", label: "Jacksonville at sunset", category: "Place" },
  { url: "/starter-photos/jacksonville-bridge-day.jpg", label: "Main Street Bridge", category: "Place" },
  { url: "/starter-photos/courthouse-columns.jpg", label: "Courthouse columns", category: "Architecture" },
  { url: "/starter-photos/courthouse-winter.jpg", label: "Courthouse", category: "Architecture" },
  { url: "/starter-photos/civic-columns-bw.jpg", label: "Civic building", category: "Architecture" },
  { url: "/starter-photos/law-library-classic.jpg", label: "Law library", category: "Law office" },
  { url: "/starter-photos/law-library-reading.jpg", label: "Legal research", category: "Law office" },
  { url: "/starter-photos/flag-law-books.jpg", label: "Flag & law books", category: "Law office" },
  { url: "/starter-photos/judge-signing.jpg", label: "Judge at work", category: "People" },
  { url: "/starter-photos/mentorship-desk.jpg", label: "Mentorship", category: "People" },
  { url: "/starter-photos/committee-meeting.jpg", label: "Committee meeting", category: "People" },
  { url: "/starter-photos/team-collaboration.jpg", label: "Team collaboration", category: "People" },
  { url: "/starter-photos/document-review.jpg", label: "Document review", category: "People" },
  { url: "/starter-photos/consultation.jpg", label: "Consultation", category: "People" },
  { url: "/starter-photos/conference-meeting.jpg", label: "Conference meeting", category: "People" },
  { url: "/starter-photos/handshake-office.jpg", label: "Handshake", category: "People" },
  { url: "/starter-photos/handshake-courthouse.jpg", label: "Agreement", category: "People" },
  { url: "/starter-photos/handshake-outdoor.jpg", label: "Introduction", category: "People" },
  { url: "/starter-photos/young-lawyers-outdoor.jpg", label: "Young lawyers", category: "People" },
  { url: "/starter-photos/volunteers-serving.jpg", label: "Community service", category: "Community" },
  { url: "/starter-photos/scales-window.jpg", label: "Scales of justice", category: "Symbols" },
  { url: "/starter-photos/scales-modern.jpg", label: "Scales of justice", category: "Symbols" },
];
