/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JoinIndexRouteImport } from './routes/join.index'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AppWebsiteRouteImport } from './routes/app.website'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppQaRouteImport } from './routes/app.qa'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppMeetingsRouteImport } from './routes/app.meetings'
import { Route as AppDiscoverRouteImport } from './routes/app.discover'
import { Route as AppDirectoryRouteImport } from './routes/app.directory'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCeRouteImport } from './routes/app.ce'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AcceptInviteTokenRouteImport } from './routes/accept-invite.$token'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AppWebsiteIndexRouteImport } from './routes/app.website.index'
import { Route as AppQaIndexRouteImport } from './routes/app.qa.index'
import { Route as AppOrgIndexRouteImport } from './routes/app.org.index'
import { Route as AppMessagesIndexRouteImport } from './routes/app.messages.index'
import { Route as AppCeIndexRouteImport } from './routes/app.ce.index'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as POrgSlugSlugRouteImport } from './routes/p.$orgSlug.$slug'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AppWebsiteTemplatesRouteImport } from './routes/app.website.templates'
import { Route as AppWebsiteSubmissionsRouteImport } from './routes/app.website.submissions'
import { Route as AppWebsiteSettingsRouteImport } from './routes/app.website.settings'
import { Route as AppWebsiteSectionsRouteImport } from './routes/app.website.sections'
import { Route as AppWebsitePublishedRouteImport } from './routes/app.website.published'
import { Route as AppWebsiteDomainsRouteImport } from './routes/app.website.domains'
import { Route as AppWebsiteBrandRouteImport } from './routes/app.website.brand'
import { Route as AppWebsiteAiRouteImport } from './routes/app.website.ai'
import { Route as AppQaSearchRouteImport } from './routes/app.qa.search'
import { Route as AppQaNotificationsRouteImport } from './routes/app.qa.notifications'
import { Route as AppQaCategoriesRouteImport } from './routes/app.qa.categories'
import { Route as AppQaAskRouteImport } from './routes/app.qa.ask'
import { Route as AppQaAdminRouteImport } from './routes/app.qa.admin'
import { Route as AppQaPostIdRouteImport } from './routes/app.qa.$postId'
import { Route as AppOrgSettingsRouteImport } from './routes/app.org.settings'
import { Route as AppOrgResourcesRouteImport } from './routes/app.org.resources'
import { Route as AppOrgMembersRouteImport } from './routes/app.org.members'
import { Route as AppOrgMatchingRouteImport } from './routes/app.org.matching'
import { Route as AppOrgJoinRequestsRouteImport } from './routes/app.org.join-requests'
import { Route as AppOrgInsightsRouteImport } from './routes/app.org.insights'
import { Route as AppOrgBillingRouteImport } from './routes/app.org.billing'
import { Route as AppMessagesIdRouteImport } from './routes/app.messages.$id'
import { Route as AppCeCatalogRouteImport } from './routes/app.ce.catalog'
import { Route as AppCeAdminRouteImport } from './routes/app.ce.admin'
import { Route as AppCeCourseIdRouteImport } from './routes/app.ce.$courseId'
import { Route as AppAdminUsersRouteImport } from './routes/app.admin.users'
import { Route as AppAdminOrgsRouteImport } from './routes/app.admin.orgs'
import { Route as ApiPublicWebsiteFormRouteImport } from './routes/api/public/website-form'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AppWebsitePagesIndexRouteImport } from './routes/app.website.pages.index'
import { Route as AppCeAdminIndexRouteImport } from './routes/app.ce.admin.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AppWebsitePagesNewRouteImport } from './routes/app.website.pages.new'
import { Route as AppWebsitePagesPageIdRouteImport } from './routes/app.website.pages.$pageId'
import { Route as AppCeAdminResultsRouteImport } from './routes/app.ce.admin.results'
import { Route as AppCeAdminAssignmentsRouteImport } from './routes/app.ce.admin.assignments'
import { Route as AppCeCourseIdLessonIdRouteImport } from './routes/app.ce.$courseId.$lessonId'
import { Route as ApiPublicPushDispatchRouteImport } from './routes/api/public/push.dispatch'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksQaDigestRouteImport } from './routes/api/public/hooks/qa-digest'
import { Route as ApiPublicHooksAutoPublishRouteImport } from './routes/api/public/hooks/auto-publish'
import { Route as AppWebsitePagesPageIdHistoryRouteImport } from './routes/app.website.pages.$pageId.history'
import { Route as AppCeAdminCourseCourseIdRouteImport } from './routes/app.ce.admin.course.$courseId'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinIndexRoute = JoinIndexRouteImport.update({
  id: '/join/',
  path: '/join/',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const AppWebsiteRoute = AppWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppQaRoute = AppQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMeetingsRoute = AppMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectoryRoute = AppDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCeRoute = AppCeRouteImport.update({
  id: '/ce',
  path: '/ce',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AcceptInviteTokenRoute = AcceptInviteTokenRouteImport.update({
  id: '/accept-invite/$token',
  path: '/accept-invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWebsiteIndexRoute = AppWebsiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppQaIndexRoute = AppQaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppQaRoute,
} as any)
const AppOrgIndexRoute = AppOrgIndexRouteImport.update({
  id: '/org/',
  path: '/org/',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesIndexRoute = AppMessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMessagesRoute,
} as any)
const AppCeIndexRoute = AppCeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCeRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const POrgSlugSlugRoute = POrgSlugSlugRouteImport.update({
  id: '/p/$orgSlug/$slug',
  path: '/p/$orgSlug/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWebsiteTemplatesRoute = AppWebsiteTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppWebsiteSubmissionsRoute = AppWebsiteSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppWebsiteSettingsRoute = AppWebsiteSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppWebsiteSectionsRoute = AppWebsiteSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppWebsitePublishedRoute = AppWebsitePublishedRouteImport.update({
  id: '/published',
  path: '/published',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppWebsiteDomainsRoute = AppWebsiteDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppWebsiteBrandRoute = AppWebsiteBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppWebsiteAiRoute = AppWebsiteAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppQaSearchRoute = AppQaSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppQaRoute,
} as any)
const AppQaNotificationsRoute = AppQaNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppQaRoute,
} as any)
const AppQaCategoriesRoute = AppQaCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppQaRoute,
} as any)
const AppQaAskRoute = AppQaAskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => AppQaRoute,
} as any)
const AppQaAdminRoute = AppQaAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppQaRoute,
} as any)
const AppQaPostIdRoute = AppQaPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AppQaRoute,
} as any)
const AppOrgSettingsRoute = AppOrgSettingsRouteImport.update({
  id: '/org/settings',
  path: '/org/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgResourcesRoute = AppOrgResourcesRouteImport.update({
  id: '/org/resources',
  path: '/org/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgMembersRoute = AppOrgMembersRouteImport.update({
  id: '/org/members',
  path: '/org/members',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgMatchingRoute = AppOrgMatchingRouteImport.update({
  id: '/org/matching',
  path: '/org/matching',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgJoinRequestsRoute = AppOrgJoinRequestsRouteImport.update({
  id: '/org/join-requests',
  path: '/org/join-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgInsightsRoute = AppOrgInsightsRouteImport.update({
  id: '/org/insights',
  path: '/org/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgBillingRoute = AppOrgBillingRouteImport.update({
  id: '/org/billing',
  path: '/org/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesIdRoute = AppMessagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppMessagesRoute,
} as any)
const AppCeCatalogRoute = AppCeCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppCeRoute,
} as any)
const AppCeAdminRoute = AppCeAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppCeRoute,
} as any)
const AppCeCourseIdRoute = AppCeCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AppCeRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminOrgsRoute = AppAdminOrgsRouteImport.update({
  id: '/orgs',
  path: '/orgs',
  getParentRoute: () => AppAdminRoute,
} as any)
const ApiPublicWebsiteFormRoute = ApiPublicWebsiteFormRouteImport.update({
  id: '/api/public/website-form',
  path: '/api/public/website-form',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWebsitePagesIndexRoute = AppWebsitePagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppCeAdminIndexRoute = AppCeAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCeAdminRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWebsitePagesNewRoute = AppWebsitePagesNewRouteImport.update({
  id: '/pages/new',
  path: '/pages/new',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppWebsitePagesPageIdRoute = AppWebsitePagesPageIdRouteImport.update({
  id: '/pages/$pageId',
  path: '/pages/$pageId',
  getParentRoute: () => AppWebsiteRoute,
} as any)
const AppCeAdminResultsRoute = AppCeAdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppCeAdminRoute,
} as any)
const AppCeAdminAssignmentsRoute = AppCeAdminAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppCeAdminRoute,
} as any)
const AppCeCourseIdLessonIdRoute = AppCeCourseIdLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => AppCeCourseIdRoute,
} as any)
const ApiPublicPushDispatchRoute = ApiPublicPushDispatchRouteImport.update({
  id: '/api/public/push/dispatch',
  path: '/api/public/push/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksQaDigestRoute = ApiPublicHooksQaDigestRouteImport.update({
  id: '/api/public/hooks/qa-digest',
  path: '/api/public/hooks/qa-digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAutoPublishRoute =
  ApiPublicHooksAutoPublishRouteImport.update({
    id: '/api/public/hooks/auto-publish',
    path: '/api/public/hooks/auto-publish',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWebsitePagesPageIdHistoryRoute =
  AppWebsitePagesPageIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AppWebsitePagesPageIdRoute,
  } as any)
const AppCeAdminCourseCourseIdRoute =
  AppCeAdminCourseCourseIdRouteImport.update({
    id: '/course/$courseId',
    path: '/course/$courseId',
    getParentRoute: () => AppCeAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/app/activity': typeof AppActivityRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/ce': typeof AppCeRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/directory': typeof AppDirectoryRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/messages': typeof AppMessagesRouteWithChildren
  '/app/qa': typeof AppQaRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/website': typeof AppWebsiteRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/join/$code': typeof JoinCodeRoute
  '/join/': typeof JoinIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/website-form': typeof ApiPublicWebsiteFormRoute
  '/app/admin/orgs': typeof AppAdminOrgsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/ce/$courseId': typeof AppCeCourseIdRouteWithChildren
  '/app/ce/admin': typeof AppCeAdminRouteWithChildren
  '/app/ce/catalog': typeof AppCeCatalogRoute
  '/app/messages/$id': typeof AppMessagesIdRoute
  '/app/org/billing': typeof AppOrgBillingRoute
  '/app/org/insights': typeof AppOrgInsightsRoute
  '/app/org/join-requests': typeof AppOrgJoinRequestsRoute
  '/app/org/matching': typeof AppOrgMatchingRoute
  '/app/org/members': typeof AppOrgMembersRoute
  '/app/org/resources': typeof AppOrgResourcesRoute
  '/app/org/settings': typeof AppOrgSettingsRoute
  '/app/qa/$postId': typeof AppQaPostIdRoute
  '/app/qa/admin': typeof AppQaAdminRoute
  '/app/qa/ask': typeof AppQaAskRoute
  '/app/qa/categories': typeof AppQaCategoriesRoute
  '/app/qa/notifications': typeof AppQaNotificationsRoute
  '/app/qa/search': typeof AppQaSearchRoute
  '/app/website/ai': typeof AppWebsiteAiRoute
  '/app/website/brand': typeof AppWebsiteBrandRoute
  '/app/website/domains': typeof AppWebsiteDomainsRoute
  '/app/website/published': typeof AppWebsitePublishedRoute
  '/app/website/sections': typeof AppWebsiteSectionsRoute
  '/app/website/settings': typeof AppWebsiteSettingsRoute
  '/app/website/submissions': typeof AppWebsiteSubmissionsRoute
  '/app/website/templates': typeof AppWebsiteTemplatesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/p/$orgSlug/$slug': typeof POrgSlugSlugRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/ce/': typeof AppCeIndexRoute
  '/app/messages/': typeof AppMessagesIndexRoute
  '/app/org/': typeof AppOrgIndexRoute
  '/app/qa/': typeof AppQaIndexRoute
  '/app/website/': typeof AppWebsiteIndexRoute
  '/api/public/hooks/auto-publish': typeof ApiPublicHooksAutoPublishRoute
  '/api/public/hooks/qa-digest': typeof ApiPublicHooksQaDigestRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
  '/app/ce/$courseId/$lessonId': typeof AppCeCourseIdLessonIdRoute
  '/app/ce/admin/assignments': typeof AppCeAdminAssignmentsRoute
  '/app/ce/admin/results': typeof AppCeAdminResultsRoute
  '/app/website/pages/$pageId': typeof AppWebsitePagesPageIdRouteWithChildren
  '/app/website/pages/new': typeof AppWebsitePagesNewRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/app/ce/admin/': typeof AppCeAdminIndexRoute
  '/app/website/pages/': typeof AppWebsitePagesIndexRoute
  '/app/ce/admin/course/$courseId': typeof AppCeAdminCourseCourseIdRoute
  '/app/website/pages/$pageId/history': typeof AppWebsitePagesPageIdHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/app/activity': typeof AppActivityRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/directory': typeof AppDirectoryRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/settings': typeof AppSettingsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/join/$code': typeof JoinCodeRoute
  '/join': typeof JoinIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/website-form': typeof ApiPublicWebsiteFormRoute
  '/app/admin/orgs': typeof AppAdminOrgsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/ce/$courseId': typeof AppCeCourseIdRouteWithChildren
  '/app/ce/catalog': typeof AppCeCatalogRoute
  '/app/messages/$id': typeof AppMessagesIdRoute
  '/app/org/billing': typeof AppOrgBillingRoute
  '/app/org/insights': typeof AppOrgInsightsRoute
  '/app/org/join-requests': typeof AppOrgJoinRequestsRoute
  '/app/org/matching': typeof AppOrgMatchingRoute
  '/app/org/members': typeof AppOrgMembersRoute
  '/app/org/resources': typeof AppOrgResourcesRoute
  '/app/org/settings': typeof AppOrgSettingsRoute
  '/app/qa/$postId': typeof AppQaPostIdRoute
  '/app/qa/admin': typeof AppQaAdminRoute
  '/app/qa/ask': typeof AppQaAskRoute
  '/app/qa/categories': typeof AppQaCategoriesRoute
  '/app/qa/notifications': typeof AppQaNotificationsRoute
  '/app/qa/search': typeof AppQaSearchRoute
  '/app/website/ai': typeof AppWebsiteAiRoute
  '/app/website/brand': typeof AppWebsiteBrandRoute
  '/app/website/domains': typeof AppWebsiteDomainsRoute
  '/app/website/published': typeof AppWebsitePublishedRoute
  '/app/website/sections': typeof AppWebsiteSectionsRoute
  '/app/website/settings': typeof AppWebsiteSettingsRoute
  '/app/website/submissions': typeof AppWebsiteSubmissionsRoute
  '/app/website/templates': typeof AppWebsiteTemplatesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/p/$orgSlug/$slug': typeof POrgSlugSlugRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/ce': typeof AppCeIndexRoute
  '/app/messages': typeof AppMessagesIndexRoute
  '/app/org': typeof AppOrgIndexRoute
  '/app/qa': typeof AppQaIndexRoute
  '/app/website': typeof AppWebsiteIndexRoute
  '/api/public/hooks/auto-publish': typeof ApiPublicHooksAutoPublishRoute
  '/api/public/hooks/qa-digest': typeof ApiPublicHooksQaDigestRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
  '/app/ce/$courseId/$lessonId': typeof AppCeCourseIdLessonIdRoute
  '/app/ce/admin/assignments': typeof AppCeAdminAssignmentsRoute
  '/app/ce/admin/results': typeof AppCeAdminResultsRoute
  '/app/website/pages/$pageId': typeof AppWebsitePagesPageIdRouteWithChildren
  '/app/website/pages/new': typeof AppWebsitePagesNewRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/app/ce/admin': typeof AppCeAdminIndexRoute
  '/app/website/pages': typeof AppWebsitePagesIndexRoute
  '/app/ce/admin/course/$courseId': typeof AppCeAdminCourseCourseIdRoute
  '/app/website/pages/$pageId/history': typeof AppWebsitePagesPageIdHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/accept-invite/$token': typeof AcceptInviteTokenRoute
  '/app/activity': typeof AppActivityRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/ce': typeof AppCeRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/directory': typeof AppDirectoryRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/meetings': typeof AppMeetingsRoute
  '/app/messages': typeof AppMessagesRouteWithChildren
  '/app/qa': typeof AppQaRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/website': typeof AppWebsiteRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/join/$code': typeof JoinCodeRoute
  '/join/': typeof JoinIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/website-form': typeof ApiPublicWebsiteFormRoute
  '/app/admin/orgs': typeof AppAdminOrgsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/ce/$courseId': typeof AppCeCourseIdRouteWithChildren
  '/app/ce/admin': typeof AppCeAdminRouteWithChildren
  '/app/ce/catalog': typeof AppCeCatalogRoute
  '/app/messages/$id': typeof AppMessagesIdRoute
  '/app/org/billing': typeof AppOrgBillingRoute
  '/app/org/insights': typeof AppOrgInsightsRoute
  '/app/org/join-requests': typeof AppOrgJoinRequestsRoute
  '/app/org/matching': typeof AppOrgMatchingRoute
  '/app/org/members': typeof AppOrgMembersRoute
  '/app/org/resources': typeof AppOrgResourcesRoute
  '/app/org/settings': typeof AppOrgSettingsRoute
  '/app/qa/$postId': typeof AppQaPostIdRoute
  '/app/qa/admin': typeof AppQaAdminRoute
  '/app/qa/ask': typeof AppQaAskRoute
  '/app/qa/categories': typeof AppQaCategoriesRoute
  '/app/qa/notifications': typeof AppQaNotificationsRoute
  '/app/qa/search': typeof AppQaSearchRoute
  '/app/website/ai': typeof AppWebsiteAiRoute
  '/app/website/brand': typeof AppWebsiteBrandRoute
  '/app/website/domains': typeof AppWebsiteDomainsRoute
  '/app/website/published': typeof AppWebsitePublishedRoute
  '/app/website/sections': typeof AppWebsiteSectionsRoute
  '/app/website/settings': typeof AppWebsiteSettingsRoute
  '/app/website/submissions': typeof AppWebsiteSubmissionsRoute
  '/app/website/templates': typeof AppWebsiteTemplatesRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/p/$orgSlug/$slug': typeof POrgSlugSlugRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/ce/': typeof AppCeIndexRoute
  '/app/messages/': typeof AppMessagesIndexRoute
  '/app/org/': typeof AppOrgIndexRoute
  '/app/qa/': typeof AppQaIndexRoute
  '/app/website/': typeof AppWebsiteIndexRoute
  '/api/public/hooks/auto-publish': typeof ApiPublicHooksAutoPublishRoute
  '/api/public/hooks/qa-digest': typeof ApiPublicHooksQaDigestRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
  '/app/ce/$courseId/$lessonId': typeof AppCeCourseIdLessonIdRoute
  '/app/ce/admin/assignments': typeof AppCeAdminAssignmentsRoute
  '/app/ce/admin/results': typeof AppCeAdminResultsRoute
  '/app/website/pages/$pageId': typeof AppWebsitePagesPageIdRouteWithChildren
  '/app/website/pages/new': typeof AppWebsitePagesNewRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/app/ce/admin/': typeof AppCeAdminIndexRoute
  '/app/website/pages/': typeof AppWebsitePagesIndexRoute
  '/app/ce/admin/course/$courseId': typeof AppCeAdminCourseCourseIdRoute
  '/app/website/pages/$pageId/history': typeof AppWebsitePagesPageIdHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/checkout'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/privacy'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/accept-invite/$token'
    | '/app/activity'
    | '/app/admin'
    | '/app/ce'
    | '/app/dashboard'
    | '/app/directory'
    | '/app/discover'
    | '/app/meetings'
    | '/app/messages'
    | '/app/qa'
    | '/app/settings'
    | '/app/website'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/join/$code'
    | '/join/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/contact'
    | '/api/public/website-form'
    | '/app/admin/orgs'
    | '/app/admin/users'
    | '/app/ce/$courseId'
    | '/app/ce/admin'
    | '/app/ce/catalog'
    | '/app/messages/$id'
    | '/app/org/billing'
    | '/app/org/insights'
    | '/app/org/join-requests'
    | '/app/org/matching'
    | '/app/org/members'
    | '/app/org/resources'
    | '/app/org/settings'
    | '/app/qa/$postId'
    | '/app/qa/admin'
    | '/app/qa/ask'
    | '/app/qa/categories'
    | '/app/qa/notifications'
    | '/app/qa/search'
    | '/app/website/ai'
    | '/app/website/brand'
    | '/app/website/domains'
    | '/app/website/published'
    | '/app/website/sections'
    | '/app/website/settings'
    | '/app/website/submissions'
    | '/app/website/templates'
    | '/lovable/email/suppression'
    | '/p/$orgSlug/$slug'
    | '/app/admin/'
    | '/app/ce/'
    | '/app/messages/'
    | '/app/org/'
    | '/app/qa/'
    | '/app/website/'
    | '/api/public/hooks/auto-publish'
    | '/api/public/hooks/qa-digest'
    | '/api/public/payments/webhook'
    | '/api/public/push/dispatch'
    | '/app/ce/$courseId/$lessonId'
    | '/app/ce/admin/assignments'
    | '/app/ce/admin/results'
    | '/app/website/pages/$pageId'
    | '/app/website/pages/new'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/app/ce/admin/'
    | '/app/website/pages/'
    | '/app/ce/admin/course/$courseId'
    | '/app/website/pages/$pageId/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/checkout'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/privacy'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/accept-invite/$token'
    | '/app/activity'
    | '/app/dashboard'
    | '/app/directory'
    | '/app/discover'
    | '/app/meetings'
    | '/app/settings'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/join/$code'
    | '/join'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/contact'
    | '/api/public/website-form'
    | '/app/admin/orgs'
    | '/app/admin/users'
    | '/app/ce/$courseId'
    | '/app/ce/catalog'
    | '/app/messages/$id'
    | '/app/org/billing'
    | '/app/org/insights'
    | '/app/org/join-requests'
    | '/app/org/matching'
    | '/app/org/members'
    | '/app/org/resources'
    | '/app/org/settings'
    | '/app/qa/$postId'
    | '/app/qa/admin'
    | '/app/qa/ask'
    | '/app/qa/categories'
    | '/app/qa/notifications'
    | '/app/qa/search'
    | '/app/website/ai'
    | '/app/website/brand'
    | '/app/website/domains'
    | '/app/website/published'
    | '/app/website/sections'
    | '/app/website/settings'
    | '/app/website/submissions'
    | '/app/website/templates'
    | '/lovable/email/suppression'
    | '/p/$orgSlug/$slug'
    | '/app/admin'
    | '/app/ce'
    | '/app/messages'
    | '/app/org'
    | '/app/qa'
    | '/app/website'
    | '/api/public/hooks/auto-publish'
    | '/api/public/hooks/qa-digest'
    | '/api/public/payments/webhook'
    | '/api/public/push/dispatch'
    | '/app/ce/$courseId/$lessonId'
    | '/app/ce/admin/assignments'
    | '/app/ce/admin/results'
    | '/app/website/pages/$pageId'
    | '/app/website/pages/new'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/app/ce/admin'
    | '/app/website/pages'
    | '/app/ce/admin/course/$courseId'
    | '/app/website/pages/$pageId/history'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/checkout'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/privacy'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/unsubscribe'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/accept-invite/$token'
    | '/app/activity'
    | '/app/admin'
    | '/app/ce'
    | '/app/dashboard'
    | '/app/directory'
    | '/app/discover'
    | '/app/meetings'
    | '/app/messages'
    | '/app/qa'
    | '/app/settings'
    | '/app/website'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/join/$code'
    | '/join/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/contact'
    | '/api/public/website-form'
    | '/app/admin/orgs'
    | '/app/admin/users'
    | '/app/ce/$courseId'
    | '/app/ce/admin'
    | '/app/ce/catalog'
    | '/app/messages/$id'
    | '/app/org/billing'
    | '/app/org/insights'
    | '/app/org/join-requests'
    | '/app/org/matching'
    | '/app/org/members'
    | '/app/org/resources'
    | '/app/org/settings'
    | '/app/qa/$postId'
    | '/app/qa/admin'
    | '/app/qa/ask'
    | '/app/qa/categories'
    | '/app/qa/notifications'
    | '/app/qa/search'
    | '/app/website/ai'
    | '/app/website/brand'
    | '/app/website/domains'
    | '/app/website/published'
    | '/app/website/sections'
    | '/app/website/settings'
    | '/app/website/submissions'
    | '/app/website/templates'
    | '/lovable/email/suppression'
    | '/p/$orgSlug/$slug'
    | '/app/admin/'
    | '/app/ce/'
    | '/app/messages/'
    | '/app/org/'
    | '/app/qa/'
    | '/app/website/'
    | '/api/public/hooks/auto-publish'
    | '/api/public/hooks/qa-digest'
    | '/api/public/payments/webhook'
    | '/api/public/push/dispatch'
    | '/app/ce/$courseId/$lessonId'
    | '/app/ce/admin/assignments'
    | '/app/ce/admin/results'
    | '/app/website/pages/$pageId'
    | '/app/website/pages/new'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/app/ce/admin/'
    | '/app/website/pages/'
    | '/app/ce/admin/course/$courseId'
    | '/app/website/pages/$pageId/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CheckoutRoute: typeof CheckoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AcceptInviteTokenRoute: typeof AcceptInviteTokenRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  JoinCodeRoute: typeof JoinCodeRoute
  JoinIndexRoute: typeof JoinIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicWebsiteFormRoute: typeof ApiPublicWebsiteFormRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  POrgSlugSlugRoute: typeof POrgSlugSlugRoute
  ApiPublicHooksAutoPublishRoute: typeof ApiPublicHooksAutoPublishRoute
  ApiPublicHooksQaDigestRoute: typeof ApiPublicHooksQaDigestRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicPushDispatchRoute: typeof ApiPublicPushDispatchRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/': {
      id: '/join/'
      path: '/join'
      fullPath: '/join/'
      preLoaderRoute: typeof JoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/app/website': {
      id: '/app/website'
      path: '/website'
      fullPath: '/app/website'
      preLoaderRoute: typeof AppWebsiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/qa': {
      id: '/app/qa'
      path: '/qa'
      fullPath: '/app/qa'
      preLoaderRoute: typeof AppQaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meetings': {
      id: '/app/meetings'
      path: '/meetings'
      fullPath: '/app/meetings'
      preLoaderRoute: typeof AppMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discover': {
      id: '/app/discover'
      path: '/discover'
      fullPath: '/app/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/directory': {
      id: '/app/directory'
      path: '/directory'
      fullPath: '/app/directory'
      preLoaderRoute: typeof AppDirectoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ce': {
      id: '/app/ce'
      path: '/ce'
      fullPath: '/app/ce'
      preLoaderRoute: typeof AppCeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/accept-invite/$token': {
      id: '/accept-invite/$token'
      path: '/accept-invite/$token'
      fullPath: '/accept-invite/$token'
      preLoaderRoute: typeof AcceptInviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/website/': {
      id: '/app/website/'
      path: '/'
      fullPath: '/app/website/'
      preLoaderRoute: typeof AppWebsiteIndexRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/app/qa/': {
      id: '/app/qa/'
      path: '/'
      fullPath: '/app/qa/'
      preLoaderRoute: typeof AppQaIndexRouteImport
      parentRoute: typeof AppQaRoute
    }
    '/app/org/': {
      id: '/app/org/'
      path: '/org'
      fullPath: '/app/org/'
      preLoaderRoute: typeof AppOrgIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages/': {
      id: '/app/messages/'
      path: '/'
      fullPath: '/app/messages/'
      preLoaderRoute: typeof AppMessagesIndexRouteImport
      parentRoute: typeof AppMessagesRoute
    }
    '/app/ce/': {
      id: '/app/ce/'
      path: '/'
      fullPath: '/app/ce/'
      preLoaderRoute: typeof AppCeIndexRouteImport
      parentRoute: typeof AppCeRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/p/$orgSlug/$slug': {
      id: '/p/$orgSlug/$slug'
      path: '/p/$orgSlug/$slug'
      fullPath: '/p/$orgSlug/$slug'
      preLoaderRoute: typeof POrgSlugSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/website/templates': {
      id: '/app/website/templates'
      path: '/templates'
      fullPath: '/app/website/templates'
      preLoaderRoute: typeof AppWebsiteTemplatesRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/app/website/submissions': {
      id: '/app/website/submissions'
      path: '/submissions'
      fullPath: '/app/website/submissions'
      preLoaderRoute: typeof AppWebsiteSubmissionsRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/app/website/settings': {
      id: '/app/website/settings'
      path: '/settings'
      fullPath: '/app/website/settings'
      preLoaderRoute: typeof AppWebsiteSettingsRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/app/website/sections': {
      id: '/app/website/sections'
      path: '/sections'
      fullPath: '/app/website/sections'
      preLoaderRoute: typeof AppWebsiteSectionsRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/app/website/published': {
      id: '/app/website/published'
      path: '/published'
      fullPath: '/app/website/published'
      preLoaderRoute: typeof AppWebsitePublishedRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/app/website/domains': {
      id: '/app/website/domains'
      path: '/domains'
      fullPath: '/app/website/domains'
      preLoaderRoute: typeof AppWebsiteDomainsRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/app/website/brand': {
      id: '/app/website/brand'
      path: '/brand'
      fullPath: '/app/website/brand'
      preLoaderRoute: typeof AppWebsiteBrandRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/app/website/ai': {
      id: '/app/website/ai'
      path: '/ai'
      fullPath: '/app/website/ai'
      preLoaderRoute: typeof AppWebsiteAiRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/app/qa/search': {
      id: '/app/qa/search'
      path: '/search'
      fullPath: '/app/qa/search'
      preLoaderRoute: typeof AppQaSearchRouteImport
      parentRoute: typeof AppQaRoute
    }
    '/app/qa/notifications': {
      id: '/app/qa/notifications'
      path: '/notifications'
      fullPath: '/app/qa/notifications'
      preLoaderRoute: typeof AppQaNotificationsRouteImport
      parentRoute: typeof AppQaRoute
    }
    '/app/qa/categories': {
      id: '/app/qa/categories'
      path: '/categories'
      fullPath: '/app/qa/categories'
      preLoaderRoute: typeof AppQaCategoriesRouteImport
      parentRoute: typeof AppQaRoute
    }
    '/app/qa/ask': {
      id: '/app/qa/ask'
      path: '/ask'
      fullPath: '/app/qa/ask'
      preLoaderRoute: typeof AppQaAskRouteImport
      parentRoute: typeof AppQaRoute
    }
    '/app/qa/admin': {
      id: '/app/qa/admin'
      path: '/admin'
      fullPath: '/app/qa/admin'
      preLoaderRoute: typeof AppQaAdminRouteImport
      parentRoute: typeof AppQaRoute
    }
    '/app/qa/$postId': {
      id: '/app/qa/$postId'
      path: '/$postId'
      fullPath: '/app/qa/$postId'
      preLoaderRoute: typeof AppQaPostIdRouteImport
      parentRoute: typeof AppQaRoute
    }
    '/app/org/settings': {
      id: '/app/org/settings'
      path: '/org/settings'
      fullPath: '/app/org/settings'
      preLoaderRoute: typeof AppOrgSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/org/resources': {
      id: '/app/org/resources'
      path: '/org/resources'
      fullPath: '/app/org/resources'
      preLoaderRoute: typeof AppOrgResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/org/members': {
      id: '/app/org/members'
      path: '/org/members'
      fullPath: '/app/org/members'
      preLoaderRoute: typeof AppOrgMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/org/matching': {
      id: '/app/org/matching'
      path: '/org/matching'
      fullPath: '/app/org/matching'
      preLoaderRoute: typeof AppOrgMatchingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/org/join-requests': {
      id: '/app/org/join-requests'
      path: '/org/join-requests'
      fullPath: '/app/org/join-requests'
      preLoaderRoute: typeof AppOrgJoinRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/org/insights': {
      id: '/app/org/insights'
      path: '/org/insights'
      fullPath: '/app/org/insights'
      preLoaderRoute: typeof AppOrgInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/org/billing': {
      id: '/app/org/billing'
      path: '/org/billing'
      fullPath: '/app/org/billing'
      preLoaderRoute: typeof AppOrgBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages/$id': {
      id: '/app/messages/$id'
      path: '/$id'
      fullPath: '/app/messages/$id'
      preLoaderRoute: typeof AppMessagesIdRouteImport
      parentRoute: typeof AppMessagesRoute
    }
    '/app/ce/catalog': {
      id: '/app/ce/catalog'
      path: '/catalog'
      fullPath: '/app/ce/catalog'
      preLoaderRoute: typeof AppCeCatalogRouteImport
      parentRoute: typeof AppCeRoute
    }
    '/app/ce/admin': {
      id: '/app/ce/admin'
      path: '/admin'
      fullPath: '/app/ce/admin'
      preLoaderRoute: typeof AppCeAdminRouteImport
      parentRoute: typeof AppCeRoute
    }
    '/app/ce/$courseId': {
      id: '/app/ce/$courseId'
      path: '/$courseId'
      fullPath: '/app/ce/$courseId'
      preLoaderRoute: typeof AppCeCourseIdRouteImport
      parentRoute: typeof AppCeRoute
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/orgs': {
      id: '/app/admin/orgs'
      path: '/orgs'
      fullPath: '/app/admin/orgs'
      preLoaderRoute: typeof AppAdminOrgsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/api/public/website-form': {
      id: '/api/public/website-form'
      path: '/api/public/website-form'
      fullPath: '/api/public/website-form'
      preLoaderRoute: typeof ApiPublicWebsiteFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/website/pages/': {
      id: '/app/website/pages/'
      path: '/pages'
      fullPath: '/app/website/pages/'
      preLoaderRoute: typeof AppWebsitePagesIndexRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/app/ce/admin/': {
      id: '/app/ce/admin/'
      path: '/'
      fullPath: '/app/ce/admin/'
      preLoaderRoute: typeof AppCeAdminIndexRouteImport
      parentRoute: typeof AppCeAdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/website/pages/new': {
      id: '/app/website/pages/new'
      path: '/pages/new'
      fullPath: '/app/website/pages/new'
      preLoaderRoute: typeof AppWebsitePagesNewRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/app/website/pages/$pageId': {
      id: '/app/website/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/app/website/pages/$pageId'
      preLoaderRoute: typeof AppWebsitePagesPageIdRouteImport
      parentRoute: typeof AppWebsiteRoute
    }
    '/app/ce/admin/results': {
      id: '/app/ce/admin/results'
      path: '/results'
      fullPath: '/app/ce/admin/results'
      preLoaderRoute: typeof AppCeAdminResultsRouteImport
      parentRoute: typeof AppCeAdminRoute
    }
    '/app/ce/admin/assignments': {
      id: '/app/ce/admin/assignments'
      path: '/assignments'
      fullPath: '/app/ce/admin/assignments'
      preLoaderRoute: typeof AppCeAdminAssignmentsRouteImport
      parentRoute: typeof AppCeAdminRoute
    }
    '/app/ce/$courseId/$lessonId': {
      id: '/app/ce/$courseId/$lessonId'
      path: '/$lessonId'
      fullPath: '/app/ce/$courseId/$lessonId'
      preLoaderRoute: typeof AppCeCourseIdLessonIdRouteImport
      parentRoute: typeof AppCeCourseIdRoute
    }
    '/api/public/push/dispatch': {
      id: '/api/public/push/dispatch'
      path: '/api/public/push/dispatch'
      fullPath: '/api/public/push/dispatch'
      preLoaderRoute: typeof ApiPublicPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/qa-digest': {
      id: '/api/public/hooks/qa-digest'
      path: '/api/public/hooks/qa-digest'
      fullPath: '/api/public/hooks/qa-digest'
      preLoaderRoute: typeof ApiPublicHooksQaDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-publish': {
      id: '/api/public/hooks/auto-publish'
      path: '/api/public/hooks/auto-publish'
      fullPath: '/api/public/hooks/auto-publish'
      preLoaderRoute: typeof ApiPublicHooksAutoPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/website/pages/$pageId/history': {
      id: '/app/website/pages/$pageId/history'
      path: '/history'
      fullPath: '/app/website/pages/$pageId/history'
      preLoaderRoute: typeof AppWebsitePagesPageIdHistoryRouteImport
      parentRoute: typeof AppWebsitePagesPageIdRoute
    }
    '/app/ce/admin/course/$courseId': {
      id: '/app/ce/admin/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/app/ce/admin/course/$courseId'
      preLoaderRoute: typeof AppCeAdminCourseCourseIdRouteImport
      parentRoute: typeof AppCeAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminOrgsRoute: typeof AppAdminOrgsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminOrgsRoute: AppAdminOrgsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppCeCourseIdRouteChildren {
  AppCeCourseIdLessonIdRoute: typeof AppCeCourseIdLessonIdRoute
}

const AppCeCourseIdRouteChildren: AppCeCourseIdRouteChildren = {
  AppCeCourseIdLessonIdRoute: AppCeCourseIdLessonIdRoute,
}

const AppCeCourseIdRouteWithChildren = AppCeCourseIdRoute._addFileChildren(
  AppCeCourseIdRouteChildren,
)

interface AppCeAdminRouteChildren {
  AppCeAdminAssignmentsRoute: typeof AppCeAdminAssignmentsRoute
  AppCeAdminResultsRoute: typeof AppCeAdminResultsRoute
  AppCeAdminIndexRoute: typeof AppCeAdminIndexRoute
  AppCeAdminCourseCourseIdRoute: typeof AppCeAdminCourseCourseIdRoute
}

const AppCeAdminRouteChildren: AppCeAdminRouteChildren = {
  AppCeAdminAssignmentsRoute: AppCeAdminAssignmentsRoute,
  AppCeAdminResultsRoute: AppCeAdminResultsRoute,
  AppCeAdminIndexRoute: AppCeAdminIndexRoute,
  AppCeAdminCourseCourseIdRoute: AppCeAdminCourseCourseIdRoute,
}

const AppCeAdminRouteWithChildren = AppCeAdminRoute._addFileChildren(
  AppCeAdminRouteChildren,
)

interface AppCeRouteChildren {
  AppCeCourseIdRoute: typeof AppCeCourseIdRouteWithChildren
  AppCeAdminRoute: typeof AppCeAdminRouteWithChildren
  AppCeCatalogRoute: typeof AppCeCatalogRoute
  AppCeIndexRoute: typeof AppCeIndexRoute
}

const AppCeRouteChildren: AppCeRouteChildren = {
  AppCeCourseIdRoute: AppCeCourseIdRouteWithChildren,
  AppCeAdminRoute: AppCeAdminRouteWithChildren,
  AppCeCatalogRoute: AppCeCatalogRoute,
  AppCeIndexRoute: AppCeIndexRoute,
}

const AppCeRouteWithChildren = AppCeRoute._addFileChildren(AppCeRouteChildren)

interface AppMessagesRouteChildren {
  AppMessagesIdRoute: typeof AppMessagesIdRoute
  AppMessagesIndexRoute: typeof AppMessagesIndexRoute
}

const AppMessagesRouteChildren: AppMessagesRouteChildren = {
  AppMessagesIdRoute: AppMessagesIdRoute,
  AppMessagesIndexRoute: AppMessagesIndexRoute,
}

const AppMessagesRouteWithChildren = AppMessagesRoute._addFileChildren(
  AppMessagesRouteChildren,
)

interface AppQaRouteChildren {
  AppQaPostIdRoute: typeof AppQaPostIdRoute
  AppQaAdminRoute: typeof AppQaAdminRoute
  AppQaAskRoute: typeof AppQaAskRoute
  AppQaCategoriesRoute: typeof AppQaCategoriesRoute
  AppQaNotificationsRoute: typeof AppQaNotificationsRoute
  AppQaSearchRoute: typeof AppQaSearchRoute
  AppQaIndexRoute: typeof AppQaIndexRoute
}

const AppQaRouteChildren: AppQaRouteChildren = {
  AppQaPostIdRoute: AppQaPostIdRoute,
  AppQaAdminRoute: AppQaAdminRoute,
  AppQaAskRoute: AppQaAskRoute,
  AppQaCategoriesRoute: AppQaCategoriesRoute,
  AppQaNotificationsRoute: AppQaNotificationsRoute,
  AppQaSearchRoute: AppQaSearchRoute,
  AppQaIndexRoute: AppQaIndexRoute,
}

const AppQaRouteWithChildren = AppQaRoute._addFileChildren(AppQaRouteChildren)

interface AppWebsitePagesPageIdRouteChildren {
  AppWebsitePagesPageIdHistoryRoute: typeof AppWebsitePagesPageIdHistoryRoute
}

const AppWebsitePagesPageIdRouteChildren: AppWebsitePagesPageIdRouteChildren = {
  AppWebsitePagesPageIdHistoryRoute: AppWebsitePagesPageIdHistoryRoute,
}

const AppWebsitePagesPageIdRouteWithChildren =
  AppWebsitePagesPageIdRoute._addFileChildren(
    AppWebsitePagesPageIdRouteChildren,
  )

interface AppWebsiteRouteChildren {
  AppWebsiteAiRoute: typeof AppWebsiteAiRoute
  AppWebsiteBrandRoute: typeof AppWebsiteBrandRoute
  AppWebsiteDomainsRoute: typeof AppWebsiteDomainsRoute
  AppWebsitePublishedRoute: typeof AppWebsitePublishedRoute
  AppWebsiteSectionsRoute: typeof AppWebsiteSectionsRoute
  AppWebsiteSettingsRoute: typeof AppWebsiteSettingsRoute
  AppWebsiteSubmissionsRoute: typeof AppWebsiteSubmissionsRoute
  AppWebsiteTemplatesRoute: typeof AppWebsiteTemplatesRoute
  AppWebsiteIndexRoute: typeof AppWebsiteIndexRoute
  AppWebsitePagesPageIdRoute: typeof AppWebsitePagesPageIdRouteWithChildren
  AppWebsitePagesNewRoute: typeof AppWebsitePagesNewRoute
  AppWebsitePagesIndexRoute: typeof AppWebsitePagesIndexRoute
}

const AppWebsiteRouteChildren: AppWebsiteRouteChildren = {
  AppWebsiteAiRoute: AppWebsiteAiRoute,
  AppWebsiteBrandRoute: AppWebsiteBrandRoute,
  AppWebsiteDomainsRoute: AppWebsiteDomainsRoute,
  AppWebsitePublishedRoute: AppWebsitePublishedRoute,
  AppWebsiteSectionsRoute: AppWebsiteSectionsRoute,
  AppWebsiteSettingsRoute: AppWebsiteSettingsRoute,
  AppWebsiteSubmissionsRoute: AppWebsiteSubmissionsRoute,
  AppWebsiteTemplatesRoute: AppWebsiteTemplatesRoute,
  AppWebsiteIndexRoute: AppWebsiteIndexRoute,
  AppWebsitePagesPageIdRoute: AppWebsitePagesPageIdRouteWithChildren,
  AppWebsitePagesNewRoute: AppWebsitePagesNewRoute,
  AppWebsitePagesIndexRoute: AppWebsitePagesIndexRoute,
}

const AppWebsiteRouteWithChildren = AppWebsiteRoute._addFileChildren(
  AppWebsiteRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppCeRoute: typeof AppCeRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDirectoryRoute: typeof AppDirectoryRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppMeetingsRoute: typeof AppMeetingsRoute
  AppMessagesRoute: typeof AppMessagesRouteWithChildren
  AppQaRoute: typeof AppQaRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppWebsiteRoute: typeof AppWebsiteRouteWithChildren
  AppOrgBillingRoute: typeof AppOrgBillingRoute
  AppOrgInsightsRoute: typeof AppOrgInsightsRoute
  AppOrgJoinRequestsRoute: typeof AppOrgJoinRequestsRoute
  AppOrgMatchingRoute: typeof AppOrgMatchingRoute
  AppOrgMembersRoute: typeof AppOrgMembersRoute
  AppOrgResourcesRoute: typeof AppOrgResourcesRoute
  AppOrgSettingsRoute: typeof AppOrgSettingsRoute
  AppOrgIndexRoute: typeof AppOrgIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppCeRoute: AppCeRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDirectoryRoute: AppDirectoryRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppMeetingsRoute: AppMeetingsRoute,
  AppMessagesRoute: AppMessagesRouteWithChildren,
  AppQaRoute: AppQaRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppWebsiteRoute: AppWebsiteRouteWithChildren,
  AppOrgBillingRoute: AppOrgBillingRoute,
  AppOrgInsightsRoute: AppOrgInsightsRoute,
  AppOrgJoinRequestsRoute: AppOrgJoinRequestsRoute,
  AppOrgMatchingRoute: AppOrgMatchingRoute,
  AppOrgMembersRoute: AppOrgMembersRoute,
  AppOrgResourcesRoute: AppOrgResourcesRoute,
  AppOrgSettingsRoute: AppOrgSettingsRoute,
  AppOrgIndexRoute: AppOrgIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CheckoutRoute: CheckoutRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AcceptInviteTokenRoute: AcceptInviteTokenRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  JoinCodeRoute: JoinCodeRoute,
  JoinIndexRoute: JoinIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicWebsiteFormRoute: ApiPublicWebsiteFormRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  POrgSlugSlugRoute: POrgSlugSlugRoute,
  ApiPublicHooksAutoPublishRoute: ApiPublicHooksAutoPublishRoute,
  ApiPublicHooksQaDigestRoute: ApiPublicHooksQaDigestRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicPushDispatchRoute: ApiPublicPushDispatchRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
